### PR TITLE
Did some code rework :)

### PR DESCRIPTION
**Pull request by m4rcsch**
Hi Tom,

thanks for the helper and adapter. I did some rework on it and created some testStubs.

### CODE REVIEW

**Comment by tmaiaroto** [comment]
Cool, but you don't need to pass $credentials at all. Facebook API handles that. I'm going to pull in your changes but remove that. It doesn't make sense to pass a request object at all - especially not just for some environment variables =) What I want to do is get at the configuration for the adapter. Using that, we can set the options there (much better place) and perhaps $options passed to check() can still be used to override some things set in the config so there's a case by case override.

**Comment by tmaiaroto** [comment]
Or scratch that, I guess it has to be passed...But I still would like to grab the config information for a few things.

**Comment by m4rcsch** [comment]
sure.

i just named it $credentials, because i copied it from the form adapter, or was it the http adapter? ;)
then we should think about reorder the config. maybe in two parts.. not sure, will write a proposal ok?

**Comment by tmaiaroto** [comment]
I think it's fine. I didn't realize it was needed. I'm not sure why it is...But that's ok. Look at the updates I made to pull in the adapter's config values though. I think something in that direction is good for being able to easily switch up behaviors. For example, one configuration has the login with a popup, the other has the login as "page" so it redirects... There's a few other options but the most notable is "next" so each configuration can redirect to a different location.

In a real world example...I may have two different configurations for my CMS. One that is presented to admin users and one that is presented to front end public users. So the redirects and maybe other options, are different.

What I think would also be neat (and I don't think this is the auth adapter anymore) is if you can also set configurations to change the requested Facebook permissions. So you can use the same li3_facebook plugin for multiple Facebook apps that are hosted through your one single lithium app. Each with their own login configuration and each with their own settings for appid, secret, and permissions.

**Comment by m4rcsch** [comment]
yeah. sounds great! (the multi fb thing)

I used the env, because i think its better to use the framework instead of the superglobals.
btw. ive forked the li3_access lib and implemented a RBAC Adapter, like the proposal on lithify.me (the role thing)

**Comment by tmaiaroto** [comment]
Yea I agree with the env(), it's a good idea.
...and I REALLY gotta see that RBAC adapter, cool!

**Comment by m4rcsch** [comment]
..done. pull request is pending :)

**Pull request merged**
